DEFAULT_EXTENSION_NAME: "PSC"
DEFAULT_VERSION: "0.4.9.2"
DEFAULT_PROXY_HOST: "127.0.0.1"
DEFAULT_PROXY_PORT: 7777
DEFAULT_PROXY_USERNAME: ""
DEFAULT_PROXY_PASSWORD: ""
DEFAULT_PROXY_TIMEOUT: 5000
DEFAULT_DOMAIN_REGX: ""
DEFAULT_SUFFIX_REGX: "js|css|jpeg|gif|jpg|png|pdf|rar|zip|docx|doc|svg|jpeg|ico|woff|woff2|ttf|otf"
DEFAULT_INTERVAL_TIME: 5000
DEFAULT_SELECTED_UNIQ: false
DEFAULT_SELECTED_PARAM: false
DEFAULT_SELECTED_SMART: false
DEFAULT_HASH_MAP_LIMIT: 500
DEFAULT_HASH_SET_LIMIT: 1000